permalink: /:year/:month/:day/:title/
title: Schauderhaft

include: ['_pages']

email: info@schauderhaft.de
github_username: schauder
twitter_username: jensschauder

# Build settings
markdown: kramdown
future: true

gems:
  - jekyll-feed
  - jekyll-redirect-from

feed:
  path: feed

collections:
  events: